# Generated by Django 2.1.2 on 2018-11-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('times', models.IntegerField(default=0)),
                ('hot_point', models.IntegerField(default=0)),
            ],
        ),
    ]
